# Generated by Django 4.1 on 2022-08-13 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hannahTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_text1', models.CharField(default='Home', max_length=50, verbose_name='nav text 1')),
                ('nav_text2', models.CharField(default='Resume', max_length=50, verbose_name='nav text 2')),
                ('nav_text3', models.CharField(default='Contact', max_length=50, verbose_name='nav text 3')),
                ('page_title', models.CharField(default='Product Designer', max_length=50, verbose_name='page title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner of website')),
            ],
        ),
    ]
