# Generated by Django 4.1 on 2022-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webella', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_dashboard',
            name='website_type',
            field=models.CharField(choices=[('B', 'BLOG'), ('P', 'PORTFOLIO'), ('U', 'UNDECLARED')], default='U', max_length=50),
        ),
    ]
