# Generated by Django 4.1 on 2022-08-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webella', '0002_user_dashboard_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_dashboard',
            name='name',
        ),
    ]
