# Generated by Django 4.1 on 2022-08-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hannahtemplate',
            name='hero_text_big',
            field=models.CharField(default='I am Hannah James', max_length=50, verbose_name='hero big text'),
        ),
        migrations.AddField(
            model_name='hannahtemplate',
            name='hero_text_small',
            field=models.CharField(default='Hi there!', max_length=50, verbose_name='hero small text'),
        ),
    ]
