# Generated by Django 4.1 on 2022-08-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_hannahtemplate_hero_text_big_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hannahtemplate',
            name='background_color',
            field=models.CharField(default='#f4e0e0', max_length=50, verbose_name='background color'),
        ),
        migrations.AddField(
            model_name='hannahtemplate',
            name='hero_div_color',
            field=models.CharField(default='#fcbbbb', max_length=50, verbose_name='landing page color'),
        ),
    ]
