# Generated by Django 4.1 on 2022-08-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_hannahtemplate_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hannahtemplate',
            name='about_paragragh',
            field=models.TextField(default='lorem ipsum', verbose_name='About paragragh'),
        ),
        migrations.AddField(
            model_name='hannahtemplate',
            name='hero_image',
            field=models.ImageField(blank='True', default='hannah.png', upload_to='', verbose_name='Hero image'),
        ),
    ]
