# Generated by Django 4.1 on 2022-08-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_remove_hannahtemplate_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hannahtemplate',
            name='about_paragragh',
        ),
        migrations.AddField(
            model_name='hannahtemplate',
            name='about_paragraph',
            field=models.TextField(default='lorem ipsum', verbose_name='About paragraph'),
        ),
    ]
